name: 'Copilot Metrics Retention'
description: 'This Action is designed to persistently store Copilot Usage Metrics data over time in a JSON file format.'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  org_name: 
    description: 'Organization name'
    required: true
  json_path:
    description: 'JSON File path'
    required: false
    default: 'metrics.json'
runs:
  using: 'node16'
  main: 'app/index.js'
